'use client'

import { useState } from 'react'

interface AIAnalysisProps {
  politicianId: string
  politicianName: string
}

export default function AIAnalysis({ politicianId, politicianName }: AIAnalysisProps) {
  const [analysis, setAnalysis] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function generate() {
    setLoading(true)
    setError(null)
    try {
      const res = await fetch('/api/analysis', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ politicianId }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error ?? 'Failed')
      setAnalysis(data.analysis)
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Something went wrong')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: '12px', padding: '24px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: analysis ? '16px' : '0' }}>
        <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '1.1rem', fontWeight: 700, color: 'var(--text-primary)' }}>
          AI Integrity Analysis
        </h2>
        {!analysis && (
          <button
            onClick={generate}
            disabled={loading}
            style={{
              background: loading ? 'var(--border)' : 'var(--red)',
              color: loading ? 'var(--text-muted)' : 'white',
              border: 'none',
              borderRadius: '6px',
              padding: '8px 16px',
              fontSize: '0.78rem',
              fontWeight: 600,
              cursor: loading ? 'not-allowed' : 'pointer',
              fontFamily: 'var(--font-mono)',
              letterSpacing: '0.04em',
              transition: 'all 0.2s ease',
            }}
          >
            {loading ? 'Analyzing...' : `Analyze ${politicianName.split(' ').pop()}`}
          </button>
        )}
        {analysis && (
          <button
            onClick={generate}
            disabled={loading}
            style={{
              background: 'transparent',
              color: 'var(--text-muted)',
              border: '1px solid var(--border)',
              borderRadius: '6px',
              padding: '6px 12px',
              fontSize: '0.72rem',
              cursor: 'pointer',
              fontFamily: 'var(--font-mono)',
            }}
          >
            {loading ? 'Regenerating...' : 'Regenerate'}
          </button>
        )}
      </div>

      {error && (
        <div style={{ color: 'var(--red)', fontSize: '0.8rem', marginTop: '12px' }}>{error}</div>
      )}

      {loading && !analysis && (
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginTop: '12px' }}>
          <div style={{ width: '6px', height: '6px', borderRadius: '50%', background: 'var(--red)', animation: 'pulse-dot 1.2s ease infinite' }} />
          <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>
            Claude is reading the record...
          </span>
        </div>
      )}

      {analysis && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
          {analysis.split('\n\n').map((para, i) => (
            <p key={i} style={{ fontSize: '0.88rem', color: 'var(--text-secondary)', lineHeight: 1.7 }}>
              {para.replace(/\*\*/g, '')}
            </p>
          ))}
          <div style={{ fontSize: '0.65rem', color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', paddingTop: '8px', borderTop: '1px solid var(--border)' }}>
            Generated by Claude AI · For accountability purposes only
          </div>
        </div>
      )}
    </div>
  )
}